security:
    # Proveedores de usuarios que pueden usar los firewalls:
    providers:
        app_user_provider:
            entity:
                class: App\Entity\Usuario  # Clase correcta
                property: nombreUsuario    # Se usa 'nombreUsuario' en vez de 'email'
    
    # Hasheo de las claves de los usuarios
    password_hashers:
        App\Entity\Usuario:
            algorithm: auto  # Symfony elegirá el mejor algoritmo automáticamente
    
    # Firewalls
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: app_user_provider
            user_checker: App\Security\UserChecker
            form_login:
                login_path: ctrl_login 
                check_path: ctrl_login
                default_target_path: /home  
            logout:
                path: ctrl_logout 
                target: ctrl_login

    # Control de acceso basado en roles
    access_control:
        - { path: ^/usuarios, roles: ROLE_USER }  # 🚀 Protege la ruta /usuarios para usuarios logueados
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/profile, roles: ROLE_USER }




