security:
    # Proveedores de usuarios que pueden usar los firewalls:
    providers:
        app_user_provider:
            entity:
                class: App\Entity\Usuario  # Cambié la entidad de Medico a Usuario
                property: email            # Usaremos el email como identificador único
    
    # Hasheo de las claves de los usuarios
    password_hashers:
        App\Entity\Usuario:
            algorithm: auto  # Symfony elegirá el mejor algoritmo automáticamente
    
    # Firewalls
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: app_user_provider
            form_login:
                login_path: app_login
                check_path: app_login
                default_target_path: app_home  # Página a la que se redirige tras login exitoso
            logout:
                path: /logout
                target: app_login

    # Control de acceso basado en roles
    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/profile, roles: ROLE_USER }ss