security:
    # Proveedores de usuarios que pueden usar los firewalls:
    providers:
        app_user_provider:
            entity:
                class: App\Entity\Usuario  # Clase correcta
                property: nombreUsuario    # Se usa 'nombreUsuario' en vez de 'email'
    
    # Hasheo de las claves de los usuarios
    password_hashers:
        App\Entity\Usuario:
            algorithm: auto  # Symfony elegirá el mejor algoritmo automáticamente
    
    # Firewalls
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: app_user_provider
            form_login:
                login_path: ctrl_login  # Corregido (antes era app_login)
                check_path: ctrl_login  # Corregido (antes era app_login)
                default_target_path: /home  # Verifica que esta ruta exista
            logout:
                path: ctrl_logout  # Corregido (antes era /logout)
                target: ctrl_login  # Redirige al login tras cerrar sesión

    # Control de acceso basado en roles
    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/profile, roles: ROLE_USER }
