parameters:

services:
    # Default configuration for services
    _defaults:
        autowire: true
        autoconfigure: true

    # Registro explícito del UserChecker
    App\Security\UserChecker:
        tags:
            - { name: 'security.user_checker', firewall: 'main' }

    # Registro automático de clases en src/
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
